# Generated by Django 3.0.1 on 2019-12-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=250, verbose_name='Длинная ссылка')),
                ('short_url', models.URLField(max_length=250, verbose_name='Короткая ссылка')),
                ('hash', models.CharField(max_length=8, unique=True, verbose_name='Ключ ссылки')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip адрес посетителя')),
                ('user_agent', models.CharField(blank=True, max_length=150, verbose_name='User-agent посетителя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время посещение')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='short_link.ShortUrl', verbose_name='Ссылка')),
            ],
        ),
    ]
